services:

  front.twig.flofit_features:
      class: FrontBundle\Twig\FlofitTemplateFeatures
      arguments: ["@service_container", "@security.token_storage"]
      tags: [ name: twig.extension ]


  front.menu_listener:
      class: FrontBundle\EventListener\ConfigureMenuListener
      tags:
        - { name: kernel.event_listener, event: front.menu_configure_event, method: onMenuConfigure }
      arguments:
          ["@service_container"]


  front.popup_service:
          class: FrontBundle\Twig\PopupService
          arguments: ["@service_container"]
          tags: [ name: twig.extension ]

