version: '2'

services:

  php_fpm:
    restart: always
    build:
      context: .
      dockerfile: docker/phpFpm/nuc/Dockerfile
    links:
      - mysql:mysql
      - redis
      - elasticsearch
    ports:
      #php-fpm
      - "9092:9090"
      #supervisor
      - "9003:9003"
    expose:
      - "9003"
    volumes:
      - .:/var/app

  nginx:
    restart: always
    image: modpreneur/necktie-nginx:0.3
    ports:
        - 8888:80
    links:
        - php_fpm
    volumes_from:
        - php_fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx

  elasticsearch:
    restart: always
    extends:
      file: docker-compose.yml
      service: elasticsearch

  redis:
    restart: always
    extends:
      file: docker-compose.yml
      service: redis

  mysql:
    restart: always
    extends:
      file: docker-compose.yml
      service: mysql