version: '2'
services:


  php_fpm:
    image: modpreneur/necktie-fpm-test:0.7
    links:
#      - mysql:mysql
      - postgres:database
      - redis
      - rabbit_mq
      - elasticsearch
      - electron_render_service
    ports:
      #php-fpm
      - "9090:9090"
      #supervisor
      - "9002:9002"
    expose:
      - "9002"
    volumes:
      - .:/var/app

  nginx:
    image: modpreneur/necktie-nginx:0.3
    ports:
        - 8000:80
    links:
        - php_fpm
    volumes_from:
        - php_fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  rabbit_mq:
    extends:
      file: docker-compose.yml
      service: rabbit_mq

  electron_render_service:
    extends:
      file: docker-compose.yml
      service: electron_render_service


  hub:
    image: selenium/hub
    ports:
      - 4444:4444


  chrome:
    image: selenium/standalone-chrome-debug
    ports:
        - 5900:5900
        - 5901:5901
        - 49160
    privileged: true
    links:
        - hub:hub
    shm_size: 1g