version: '2'
services:

  php_fpm:
    image: modpreneur/necktie-fpm-test:0.10.1
    links:
      - mysql:mysql
      - redis
      - elasticsearch
    ports:
      #php-fpm
      - "9092:9090"
      #supervisor
      - "9003:9003"
    expose:
      - "9003"
    volumes:
      - .:/var/app

  nginx:
    image: modpreneur/necktie-nginx:0.3
    ports:
        - 8888:80
    links:
        - php_fpm
    volumes_from:
        - php_fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  mysql:
    restart: always
    extends:
      file: docker-compose.yml
      service: mysql

  hub:
    image: selenium/hub
    ports:
      - 4444:4444

  chrome:
    image: selenium/standalone-chrome-debug
    ports:
        - 5900:5900
        - 5901:5901
        - 49160
    privileged: true
    links:
        - hub:hub
    shm_size: 1g