AdminBundle:
    resource: "@AdminBundle/Controller"
    type:     annotation


FrontBundle:
    resource: "@FrontBundle/Controller"
    type:     annotation


AppBundle:
    resource: "@AppBundle/Controller"
    type:     annotation


VeniceAppBundle:
     resource: "@VeniceAdminBundle/Resources/config/routing.yml"


VeniceAdminBundle:
     resource: "@VeniceAppBundle/Resources/config/routing.yml"


VeniceFrontBundle:
     resource: "@VeniceFrontBundle/Resources/config/routing.yml"
