VeniceAppBundle:
    resource: "@VeniceAdminBundle/Resources/config/routing.yml"

VeniceAdminBundle:
    resource: "@VeniceAppBundle/Resources/config/routing.yml"

VeniceFrontBundle:
    resource: "@VeniceFrontBundle/Resources/config/routing.yml"
