security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_PAID_USER: ROLE_USER
        ROLE_ADMIN: ROLE_PAID_USER

        ROLE_ADMIN_PRODUCT_VIEW: ROLE_ADMIN
        ROLE_ADMIN_PRODUCT_EDIT: ROLE_ADMIN_PRODUCT_VIEW

        ROLE_ADMIN_BILLING_PLAN_VIEW: ROLE_ADMIN
        ROLE_ADMIN_BILLING_PLAN_EDIT: ROLE_ADMIN_BILLING_PLAN_VIEW

        ROLE_ADMIN_CONTENT_VIEW: ROLE_ADMIN
        ROLE_ADMIN_CONTENT_EDIT: ROLE_ADMIN_CONTENT_VIEW

        ROLE_ADMIN_CONTENT_PRODUCT_VIEW: ROLE_ADMIN
        ROLE_ADMIN_CONTENT_PRODUCT_EDIT: ROLE_ADMIN_CONTENT_PRODUCT_VIEW

        ROLE_ADMIN_USER_VIEW: ROLE_ADMIN
        ROLE_ADMIN_USER_EDIT: ROLE_ADMIN_USER_VIEW

        ROLE_ADMIN_BLOG_VIEW: ROLE_ADMIN
        ROLE_ADMIN_BLOG_EDIT: ROLE_ADMIN_BLOG_VIEW

        ROLE_ADMIN_PRODUCT_ACCESS_VIEW: ROLE_ADMIN

        ROLE_ADMIN_LOGGER_VIEW: ROLE_ADMIN

#       see: http://symfony.com/doc/current/cookbook/security/impersonating_user.html
        ROLE_USER_SWITCHER: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN_PRODUCT_EDIT
            - ROLE_ADMIN_BILLING_PLAN_EDIT
            - ROLE_ADMIN_CONTENT_EDIT
            - ROLE_ADMIN_CONTENT_PRODUCT_EDIT
            - ROLE_ADMIN_USER_EDIT
            - ROLE_ADMIN_BLOG_EDIT
            - ROLE_ADMIN_PaRODUCT_ACCESS_VIEW
            - ROLE_ADMIN_LOGGER_VIEW
            - ROLE_USER_SWITCHER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js|assets)
            security:   false

        notify_api:
            pattern: ^/notify/^
            anonymous: true


        main:
            pattern: ^/
            switch_user: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
            logout:
                success_handler: venice.app.logout_success_handler


    access_control:
        # pages
        - { path: ^/about, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/terms-of-use, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/privacy-policy, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/faq, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/shipping-policy, role: IS_AUTHENTICATED_ANONYMOUSLY }

        #schema
        - { path: ^/schema/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/schema/request, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/schema/new, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/schema/already-requested, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/schema/check-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/schema/change-password, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/css, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/froala, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-response, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/notify, role: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, role: [IS_AUTHENTICATED, IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY ]}

