services:

  api.security.authentication.provider:
    class: ApiBundle\Api\ApiProvider
    arguments:
        - '' # User Provider
        - '@cache.app'
    public: false


  api.security.authentication.listener:
    class: ApiBundle\Api\ApiListener
    arguments:
      - '@security.token_storage'
      - '@security.authentication.manager'
      - '@doctrine.orm.entity_manager'
    public: false

  api.controller_utils.downloads_util:
    class: ApiBundle\ControllerUtils\AppApiDownloadsUtil
    arguments:
      - "@venice.app.buy_url_generator"
      - "@trinity.services.price_string_generator"
      - "@doctrine.orm.entity_manager"
      - "@venice.app.invoice_order_service"
