<?php

namespace AppBundle\Entity\Newsletter;

use Doctrine\ORM\EntityRepository;
use GeneralBackend\CoreBundle\Entity\GlobalUser;

/**
 * QuestionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{

}
