<?php

namespace AppBundle\Entity\Newsletter;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAnswerRepository extends EntityRepository
{
    /**
     * @param  Answer     $answer
     * @param  User $globalUser
     * @return UserAnswer
     */
    public function getLastAnswer(Answer $answer, User $globalUser)
    {
        $answers = $this->findBy([
            'answer' =>$answer,
            'user' =>$globalUser
        ], ['timestamp'=>'DESC']);

        if (count($answers)) {
            return $answers[0];
        }

        return null;
    }
}
